language: node_js  #设置语言

node_js: stable  #设置相应的版本

cache:
  directories:
    - node_modules # 缓存不经常更改的内容

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - dev  #只监测dev分支，即自己的源码分支

before_install:
  - npm install -g hexo-cli

# Start: Build Lifecycle
install:
  - npm install  #安装hexo及插件

script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  # 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
  - git config user.name "wangpeng1994"
  - git config user.email "947034046@qq.com"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/github_token/${GITHUB_TOKEN}/g" ./_config.yml
  - hexo deploy

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
#   email:
#     - 947034046@qq.com
  on_success: always
  on_failure: always